### ISSUE TITLE
ISSUES

### ISSUE THREAD

**Issue by c1d2y3** [MMIRMagPie/DualVGR-VideoQA#3]
Hello, take the liberty to ask a question, does this project have an environment configuration? How is the SVQA dataset divided?

**Comment by MM-IR** [comment]
Hi, basically, you do not have to pay much attention to the env configuration, as I think most of common DL configurations should work.

- SVQA splits

This is the [official split](https://github.com/NJUPT-MCC/DualVGR-VideoQA/tree/main/SVQA_splits).

**Comment by MM-IR** [comment]
Since this is one clarification question, I am closing this now.
